const mongoose=require('mongoose');
const Schema=mongoose.Schema;
const PollSchema=new Schema({
    type:{
        type:String,
        default:'poll'
    },
    postType:{
        type:String,
        default:"poll"
    },
    community:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Community'
    },
   creator:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User'
    },
    title:{
        type:String,
        required:true
    },
    tags:[String],
    description:{
        type:String,
        required:true
    },
    options:[
        {
            count:Number,
            option:String   
        }
    ],
    expiryDate:{
        type:Date,
        required:true,
        default:Date.now
    },
    createddate:{
        type:Date,
        default:Date.now
    },
   votes:[
        {
            user:{
                type:mongoose.Schema.Types.ObjectId,
                ref:'User'
            },
            option:String
        }
    ],
    likes:[
         {
            user:{
                type:mongoose.Schema.Types.ObjectId,
                ref:'User'
            },
            poll:{
                type:mongoose.Schema.Types.ObjectId,
                ref:'Poll'
            }
         }
    ],
    comments:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'Comment'
        }
    ],
    isLiked:{
        type:Boolean,
        default:false
    },
   
    
});
module.exports=Poll=mongoose.model('Poll',PollSchema);
